"""empty message

Revision ID: 2e97ecc79bc9
Revises: 6c7f15fd6118
Create Date: 2016-11-17 16:46:39.025862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e97ecc79bc9'
down_revision = '6c7f15fd6118'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('about', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('contact', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('place', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'place')
    op.drop_column('tenants', 'image')
    op.drop_column('tenants', 'contact')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'about')
    ### end Alembic commands ###
