"""empty message

Revision ID: 5716bad042a9
Revises: 7df048a51cc8
Create Date: 2016-12-01 13:37:18.507292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5716bad042a9'
down_revision = '7df048a51cc8'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jumbo_image_name', table_name='jumbo_image')
    op.drop_column('jumbo_image', 'address')
    op.drop_column('jumbo_image', 'about')
    op.drop_column('jumbo_image', 'contact')
    op.drop_column('jumbo_image', 'name')
    op.drop_column('jumbo_image', 'email')
    op.drop_column('jumbo_image', 'phone')
    op.drop_column('jumbo_image', 'www')
    op.drop_column('jumbo_image', 'place')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jumbo_image', sa.Column('place', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('jumbo_image', sa.Column('www', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('jumbo_image', sa.Column('phone', mysql.VARCHAR(length=11), nullable=True))
    op.add_column('jumbo_image', sa.Column('email', mysql.VARCHAR(length=320), nullable=True))
    op.add_column('jumbo_image', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('jumbo_image', sa.Column('contact', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('jumbo_image', sa.Column('about', mysql.TEXT(), nullable=True))
    op.add_column('jumbo_image', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_jumbo_image_name', 'jumbo_image', ['name'], unique=False)
    ### end Alembic commands ###
