"""empty message

Revision ID: 67f931402b55
Revises: 1ceb56fdf78a
Create Date: 2016-11-17 12:58:19.075615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f931402b55'
down_revision = '1ceb56fdf78a'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_tenant',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], )
    )
    op.add_column('tenants', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('tenants', sa.Column('www', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'www')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'email')
    op.drop_table('categories_tenant')
    ### end Alembic commands ###
