"""empty message

Revision ID: 6c7f15fd6118
Revises: 67f931402b55
Create Date: 2016-11-17 13:00:26.405227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c7f15fd6118'
down_revision = '67f931402b55'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_tenants',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], )
    )
    op.drop_table('categories_tenant')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_tenant',
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='categories_tenant_ibfk_1'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='categories_tenant_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('categories_tenants')
    ### end Alembic commands ###
