"""empty message

Revision ID: a755ce4fab48
Revises: 5716bad042a9
Create Date: 2016-12-08 23:38:08.749498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a755ce4fab48'
down_revision = '5716bad042a9'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('keywords', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_keywords'), 'tenants', ['keywords'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_keywords'), table_name='tenants')
    op.drop_column('tenants', 'keywords')
    ### end Alembic commands ###
